import { LucideAngularModule } from 'lucide-angular';
import * as icons from 'lucide-angular';

const ICON_LIST = [
  'Eye',
  'EyeOff',
  'Lock',
  'ShieldCheck',
  'KeyRound',
  'ShieldAlert',
  'ShieldX',
  'ShieldOff',
  'Phone',
  'Clock',
  'CheckIcon',
  'Bookmark',
  'User',
  'Key',
  'Info',
  'FingerprintPattern',
  'ScanFace',
  'Sun',
  'CircleAlert',
  'Brain',
  'Badge',
  'IdCard',
  'Home',
  'CreditCard',
  'Send',
  'Settings',
  'Menu',
  'Receipt',
  'Smartphone',
  'Globe',
  'Wallet',
  'FileText',
  'Repeat',
  'LoaderCircle',
  'Search',
  'UserPlus',
  'ChevronRight',
  'Trash2',
  'ArrowLeft',
  'ArrowRight',
  'Calendar',
  'Calculator',
  'TrendingUp',
  'FileCheck',
  'FileChartColumnIncreasing',
  'TrendingDown',
  'CircleArrowDown',
  'Loader',
  'LayoutDashboard',
  'Ticket',
  'CirclePlus',
  'Tags',
  'ChartColumn',
  'Users',
  'CircleX',
  'Activity',
  'Plus',
  'List',
  'ChartBar',
  'Store',
  'MapPin',
  'CheckCircle',
  'PlusCircle',
  'Package',
  'Layers',
  'Mail',
  'IdCard',
  'UserCog',
  'Clock',
  'MapPin',
  'Star',
  'MessageCircle',
  'Map',
  'Calendar',
  'Store',
  'BadgePercent',
  'CalendarClock',
  'Hash',
  'Image',
  'CalendarX',
  'TicketPlus',
  'Link',
  'Headphones',
  'BadgeCheck',
  'Circle',
  'X',
  'AlertTriangle',
  'Pencil',
  'ToggleRight',
  'ToggleLeft',
  'LogOut',
  'ImagePlus',
  'Landmark'
] as const;

export const LUCIDE_ICONS = LucideAngularModule.pick(
  ICON_LIST.reduce(
    (acc, name) => {
      acc[name] = icons[name];
      return acc;
    },
    {} as Record<string, any>,
  ),
);
